"""empty message

Revision ID: d19a0331d767
Revises: 
Create Date: 2024-11-28 23:50:26.261585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19a0331d767'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.String(length=5), nullable=False),
    sa.Column('major', sa.String(length=10), nullable=False),
    sa.Column('mbti', sa.String(length=4), nullable=False),
    sa.Column('hobby', sa.String(length=25), nullable=True),
    sa.Column('contact', sa.String(length=25), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
